### PR TITLE
Bugfix/last search results not persistent

### LINKED ISSUE #16: [Bug] Last search results are not persistent after visiting a recipe
**Describe the bug**
If you access a recipe after searching, when you go back to the recipes list the last search results are reset.

**Steps to reproduce**
1. Go to local/remote recipes
2. Make a search
3. Access a recipe
4. Go back to the recipe list
5. The search results shown in step 2 have disappeared

**Expected behaviour**
When returning to the recipes list the last search results should be displayed.

**Smartphone:**
 - Device: Samsung Galaxy A10
 - OS: Android 10
 - App version: 1.0.1

### PR DESCRIPTION
**Pull request by santidrj**
#### Summary of what has been done *

- Create a new list in the MainViewModel to store the last search results.
- Update search results with the aforementioned list if the user comes from the RecipeDetailFragment.

#### Reference issues *

Closes #16 

## Type of change *
- [ ] New feature (enhancement)
- [x] Bug fix
- [ ] Documentation update  
- [ ] Other (build scripts, metadata, assets, etc.)

## Checklist *
- [x] I have performed a self-review of my own code
- [x] My code is self-explanatory  
- [ ] I have added all new string resources into strings.xml in all languages
- [x] All possible errors are properly handled  
- [x] I have tested the application with my changes and verify that all tests are passing
- [x] The documentation is up to date

### CODE REVIEW

File: app/src/main/java/org/easyrecipe/features/search/SearchViewModel.kt [hunk 1]
```diff
@@ -46,15 +45,7 @@ class SearchViewModel @Inject constructor(
...
-    private val searchRandomRecipesResultHandler = UseCaseResultHandler<SearchRecipes.Response>(
-        onSuccess = { result ->
-            recipeList.value = result.recipes
-            ScreenState.Nothing
-        },
-        onError = { ScreenState.OtherError }
-    )
-
-    fun onSearchRecipes() = launch {
+    fun onSearchRecipes(mainViewModel: MainViewModel) = launch {
```
Comment (AlbertPG) [inline app/src/main/java/org/easyrecipe/features/search/SearchViewModel.kt]: We should try to avoid injecting a `ViewModel` into another one.

File: app/src/main/java/org/easyrecipe/features/search/SearchViewModel.kt [hunk 2]
```diff
@@ -64,6 +55,7 @@ class SearchViewModel @Inject constructor(
             }
         ).onSuccess { result ->
             recipeList.value = result.recipes
+            mainViewModel.searchResultList.value = recipeList.value
```
Comment (AlbertPG) [inline app/src/main/java/org/easyrecipe/features/search/SearchViewModel.kt]: An alternative to this case would be to create an event using a `LiveData<List<Recipe>>` inside `SearchViewModel` and observe it in `SearchFragment`. The observable method should assign the value to the corresponding property from `MainViewModel`. Do not forget that you should use the backing field pattern by creating a private property of type `MutableLiveData<List<Recipe>>`

File: app/src/test/java/org/easyrecipe/features/search/SearchViewModelTest.kt [hunk 3]
```diff
@@ -58,6 +61,8 @@ class SearchViewModelTest {
         time = 75
     ))
 
+    private lateinit var mainViewModel: MainViewModel
```
Comment (AlbertPG) [inline app/src/test/java/org/easyrecipe/features/search/SearchViewModelTest.kt]: The tests should only test the behavior of a single class and all dependencies should be either a fake or a mock. In the project we should use mocks.

**Review by AlbertPG — CHANGES_REQUESTED** [review]
You should take into consideration these changes.

**Review by AlbertPG — APPROVED** [review]
Okey, I approve these changes.
