### PR TITLE
Bugfix/remote recipe tags not working properly

### LINKED ISSUE #17: [Bug] Remote recipe tags do not work properly
**Describe the bug**
When you select a tag in the remote recipes section the search does not start immediately.

**Steps to reproduce**
1. Go to remote recipes
2. Click on a tag
3. The search does not start

**Expected behaviour**
When you click on a tag the search should automatically start.

**Smartphone:**
 - Device: Samsung Galaxy A10
 - OS: Android 10
 - App version: 1.0.1

### PR DESCRIPTION
**Pull request by santidrj**
#### Summary of what has been done *

- Make the SearchFragment search for recipes when a tag is selected.
- Update dependencies

#### Reference issues *

Closes #17 

## Type of change *
- [ ] New feature (enhancement)
- [ ] New feature (enhancement) causing some functionalities to stop working
- [ ] Bug fix
- [ ] Documentation update  
- [ ] Other (build scripts, metadata, assets, etc.)

## Checklist *
- [ ] I have performed a self-review of my own code
- [ ] My code is self-explanatory  
- [ ] I have added all new string resources into strings.xml in all languages
- [ ] All possible errors are properly handled  
- [ ] I have tested the application with my changes and verify that all tests are passing
- [ ] The documentation is up to date

### CODE REVIEW

File: app/src/main/java/org/easyrecipe/features/main/MainFragment.kt [hunk 1]
```diff
@@ -31,12 +31,14 @@ import androidx.navigation.ui.AppBarConfiguration
...
 import androidx.navigation.ui.setupWithNavController
 import dagger.hilt.android.AndroidEntryPoint
+import org.easyrecipe.BuildConfig
 import org.easyrecipe.R
 import org.easyrecipe.common.BaseFragment
 import org.easyrecipe.databinding.FragmentMainBinding
 
 @AndroidEntryPoint
 class MainFragment : BaseFragment() {
+    private val UID = BuildConfig.USER_UID
```
Comment (AlbertPG) [inline app/src/main/java/org/easyrecipe/features/main/MainFragment.kt]: This property should be renamed as `uid`.

**Review by AlbertPG — CHANGES_REQUESTED** [review]
Take a look at the change that I suggest to you.

**Review by AlbertPG — APPROVED** [review]
Okey, I approve it
